"use strict";

const MAX_STORED_DATA_AGE_MS = 12 * 60 * 60 * 1000;
const DEFAULT_FORMAT = "LP";

const DESCRIPTION_FIELDS = [
  {
    key: "artist",
    displayName: "Artist",
    labels: [
      "Artist"
    ]
  },
  {
    key: "releaseTitle",
    displayName: "Title",
    labels: [
      "Title",
      "Record Title",
      "Album Title"
    ]
  },
  {
    key: "label",
    displayName: "Label",
    labels: [
      "Label",
      "Record Label"
    ]
  },
  {
    key: "catalogue",
    displayName: "Cat. No.",
    labels: [
      "Cat. No.",
      "Cat No.",
      "Cat. No",
      "Cat No",
      "Catalogue Number",
      "Catalog Number",
      "Catalogue No.",
      "Catalog No.",
      "Catalogue No",
      "Catalog No",
      "Cat. Number",
      "Cat Number",
      "Catalogue #",
      "Catalog #",
      "Cat #"
    ]
  },
  {
    key: "format",
    displayName: "Format",
    labels: [
      "Format",
      "Record Format",
      "Vinyl Format"
    ]
  }
];

const CONDITION_DESCRIPTION_FIELDS = [
  {
    key: "recordCondition",
    displayName: "Condition of Record",
    labels: [
      "Condition of Record",
      "Record Condition",
      "Condition of Vinyl",
      "Vinyl Condition"
    ]
  },
  {
    key: "sleeveCondition",
    displayName: "Condition of Sleeve",
    labels: [
      "Condition of Sleeve",
      "Sleeve Condition",
      "Condition of Cover",
      "Cover Condition"
    ]
  }
];

const ALL_DESCRIPTION_FIELDS = [
  ...DESCRIPTION_FIELDS,
  ...CONDITION_DESCRIPTION_FIELDS
];

const CONDITION_ASSISTANT_STORAGE_KEY =
  "conditionAssistantState";
const MAX_GRADE_PLUSES = 4;

const DEFAULT_CONDITION_ASSISTANT_STATE = {
  vinyl: {
    grade: "Very Good",
    pluses: 0,
    notes: ""
  },
  sleeve: {
    grade: "Very Good",
    pluses: 0,
    notes: ""
  },
  collapsed: false
};

browser.runtime.onMessage.addListener((message) => {
  if (message?.type === "FILL_EBAY_LISTING") {
    fillEbayListing();
  }
});

async function fillEbayListing() {
  try {
    const stored = await browser.storage.local.get([
      "latestDiscogsRelease",
      "autofillDescription"
    ]);

    const release = stored.latestDiscogsRelease;

    if (!release) {
      throw new Error(
        "No Discogs release is saved. Generate a title on Discogs first."
      );
    }

    if (
      typeof release.savedAt === "number" &&
      Date.now() - release.savedAt > MAX_STORED_DATA_AGE_MS
    ) {
      throw new Error(
        "The saved Discogs data is over 12 hours old. Generate it again first."
      );
    }

    // Backward-safe default for data generated by an earlier version.
    release.format = cleanText(release.format) || DEFAULT_FORMAT;

    // Ensure LP is present before the suffix even when old saved metadata
    // came from a previous extension version.
    release.ebayTitle = ensureFormatInTitle(
      release.ebayTitle,
      release.format
    );

    const titleField = findTitleField(document);

    if (!titleField) {
      throw new Error(
        "Could not find the eBay listing title field on this page."
      );
    }

    setEditableValue(titleField, release.ebayTitle);

    const descriptionEnabled =
      stored.autofillDescription !== false;

    let descriptionResult = {
      foundEditor: false,
      updatedFields: [],
      missingFields: []
    };

    if (descriptionEnabled) {
      descriptionResult = fillDescriptionAcrossDocuments(release);
    }

    if (descriptionEnabled && descriptionResult.editor) {
      scrollToDescriptionEditor(descriptionResult.editor);
    } else {
      titleField.scrollIntoView({
        behavior: "smooth",
        block: "center"
      });
    }

    let detailMessage;

    if (!descriptionEnabled) {
      detailMessage = " Description autofill is disabled in settings.";
    } else if (descriptionResult.updatedFields.length) {
      detailMessage =
        ` Description fields updated: ` +
        `${descriptionResult.updatedFields.join(", ")}.`;
    } else {
      detailMessage =
        " The title was filled, but no matching description labels were found.";
    }

    showToast(
      `eBay title filled.${detailMessage} Review the draft before saving.`,
      descriptionResult.updatedFields.length || !descriptionEnabled
        ? "success"
        : "warning"
    );

    console.log("eBay fill result:", {
      title: release.ebayTitle,
      descriptionResult
    });
  } catch (error) {
    showToast(error.message || "Unable to fill the eBay listing.", "error");
    console.error(error);
  }
}

function ensureFormatInTitle(title, format) {
  const value = cleanText(title);
  const safeFormat = cleanText(format) || DEFAULT_FORMAT;

  if (!value) {
    return value;
  }

  // Current titles already contain LP/2xLP before the optional suffix.
  if (new RegExp(`(?:^| - )${escapeRegExp(safeFormat)}(?: - |$)`, "i").test(value)) {
    return value;
  }

  // Known configured suffixes appear at the end. Insert the format
  // immediately before the suffix so the structure remains:
  // Cat No. - LP - Suffix
  const suffixPatterns = [
    /\s+-\s+JAZZ\s+-\s+GREAT COPY!$/i,
    /\s+-\s+SOUL\s+-\s+GREAT COPY!$/i,
    /\s+-\s+ROCK\s+-\s+GREAT COPY!$/i,
    /\s+-\s+REGGAE\s+-\s+GREAT COPY!$/i
  ];

  for (const pattern of suffixPatterns) {
    const match = value.match(pattern);

    if (match) {
      const suffix = match[0];
      const prefix = value.slice(0, -suffix.length);
      const rebuilt = `${prefix} - ${safeFormat}${suffix}`;

      return rebuilt.length <= 80 ? rebuilt : `${prefix} - ${safeFormat}`;
    }
  }

  const rebuilt = `${value} - ${safeFormat}`;
  return rebuilt.length <= 80 ? rebuilt : value;
}

function findTitleField(rootDocument) {
  const selectors = [
    'input[maxlength="80"]',
    'textarea[maxlength="80"]',
    'input[name*="title" i]',
    'textarea[name*="title" i]',
    'input[id*="title" i]',
    'textarea[id*="title" i]',
    'input[aria-label*="title" i]',
    'textarea[aria-label*="title" i]',
    'input[placeholder*="title" i]',
    'textarea[placeholder*="title" i]',
    '[contenteditable="true"][aria-label*="title" i]'
  ];

  const candidates = Array.from(
    rootDocument.querySelectorAll(selectors.join(","))
  )
    .filter(isVisible)
    .map((element) => ({
      element,
      score: scoreTitleField(element)
    }))
    .sort((a, b) => b.score - a.score);

  return candidates[0]?.element || null;
}

function scoreTitleField(element) {
  const searchable = [
    element.id,
    element.getAttribute("name"),
    element.getAttribute("aria-label"),
    element.getAttribute("placeholder"),
    element.getAttribute("data-testid")
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();

  let score = 0;

  if (element.maxLength === 80) {
    score += 10;
  }

  if (/\bitem\s*title\b/.test(searchable)) {
    score += 9;
  } else if (/\btitle\b/.test(searchable)) {
    score += 5;
  }

  if (/search/.test(searchable)) {
    score -= 15;
  }

  if (
    element.tagName === "INPUT" ||
    element.tagName === "TEXTAREA"
  ) {
    score += 2;
  }

  return score;
}

function fillDescriptionAcrossDocuments(release) {
  const documents = [document];

  for (const frame of document.querySelectorAll("iframe")) {
    try {
      if (frame.contentDocument) {
        documents.push(frame.contentDocument);
      }
    } catch (error) {
      console.debug("Could not inspect an eBay iframe:", error);
    }
  }

  let bestResult = {
    foundEditor: false,
    updatedFields: [],
    missingFields: DESCRIPTION_FIELDS.map(
      (field) => field.displayName
    ),
    editor: null
  };

  for (const currentDocument of documents) {
    const editors = findDescriptionEditors(currentDocument);

    for (const editor of editors) {
      const result = fillDescriptionEditor(editor, release);

      if (
        result.updatedFields.length >
        bestResult.updatedFields.length
      ) {
        bestResult = {
          ...result,
          foundEditor: true,
          editor
        };
      }

      if (
        result.updatedFields.length ===
        DESCRIPTION_FIELDS.length
      ) {
        return bestResult;
      }
    }
  }

  return bestResult;
}

function findDescriptionEditors(rootDocument) {
  const selectors = [
    'textarea[name*="description" i]',
    'textarea[id*="description" i]',
    'textarea[aria-label*="description" i]',
    'textarea[placeholder*="description" i]',
    '[contenteditable="true"][aria-label*="description" i]',
    '[contenteditable="true"][data-testid*="description" i]',
    '[role="textbox"][aria-multiline="true"]',
    '[contenteditable="true"]'
  ];

  const candidates = Array.from(
    rootDocument.querySelectorAll(selectors.join(","))
  );

  // Some rich-text editors make the document body itself editable.
  if (
    rootDocument.body &&
    (
      rootDocument.body.isContentEditable ||
      rootDocument.body.getAttribute("contenteditable") === "true"
    )
  ) {
    candidates.unshift(rootDocument.body);
  }

  return [...new Set(candidates)]
    .filter(isVisible)
    .filter((element) => countKnownLabels(element) > 0)
    .sort(
      (a, b) =>
        countKnownLabels(b) - countKnownLabels(a)
    );
}

function countKnownLabels(editor) {
  const text = getEditorText(editor);

  return DESCRIPTION_FIELDS.reduce((count, field) => {
    const found = field.labels.some((label) =>
      buildLabelRegex(label, false).test(text)
    );

    return count + (found ? 1 : 0);
  }, 0);
}

function fillDescriptionEditor(editor, release) {
  if (
    editor instanceof HTMLTextAreaElement ||
    editor instanceof HTMLInputElement
  ) {
    return fillPlainTextEditor(editor, release);
  }

  return fillRichTextEditor(editor, release);
}

function fillPlainTextEditor(editor, release) {
  let text = editor.value;
  const updatedFields = [];
  const missingFields = [];

  for (const field of DESCRIPTION_FIELDS) {
    const rawValue =
      field.key === "format"
        ? release[field.key] || DEFAULT_FORMAT
        : release[field.key];

    const value = cleanText(rawValue);

    if (!value) {
      missingFields.push(field.displayName);
      continue;
    }

    const replacement = replaceLabelledLine(
      text,
      field.labels,
      value
    );

    if (replacement.changed) {
      text = replacement.text;
      updatedFields.push(field.displayName);
    } else {
      missingFields.push(field.displayName);
    }
  }

  if (updatedFields.length) {
    setEditableValue(editor, text);
  }

  return {
    updatedFields,
    missingFields
  };
}

function replaceLabelledLine(text, labels, value) {
  for (const label of labels) {
    const expression = buildLabelRegex(label, true);

    if (expression.test(text)) {
      return {
        changed: true,
        text: text.replace(
          expression,
          (match, prefix) => `${prefix}${value}`
        )
      };
    }
  }

  return {
    changed: false,
    text
  };
}

function fillRichTextEditor(editor, release) {
  const updatedFields = [];
  const missingFields = [];

  for (const field of DESCRIPTION_FIELDS) {
    const rawValue =
      field.key === "format"
        ? release[field.key] || DEFAULT_FORMAT
        : release[field.key];

    const value = cleanText(rawValue);

    if (!value) {
      missingFields.push(field.displayName);
      continue;
    }

    const labelElement = findExactLabelElement(
      editor,
      field.labels
    );

    if (!labelElement) {
      missingFields.push(field.displayName);
      continue;
    }

    const changed = setDescriptionFieldValue(
      editor,
      labelElement,
      field.labels,
      value
    );

    if (changed) {
      updatedFields.push(field.displayName);
    } else {
      missingFields.push(field.displayName);
    }
  }

  if (updatedFields.length) {
    dispatchEditingEvents(editor);
  }

  return {
    updatedFields,
    missingFields
  };
}

function findExactLabelElement(editor, labels) {
  const selector = [
    "p",
    "div",
    "li",
    "td",
    "th",
    "span"
  ].join(",");

  const candidates = Array.from(
    editor.querySelectorAll(selector)
  )
    .filter((element) => {
      const text = getElementText(element);

      if (!text || text.length > 250) {
        return false;
      }

      return labels.some((label) =>
        isExactLabelOrInlineField(text, label)
      );
    })
    .filter((element) => {
      // Reject broad parent containers when a smaller descendant
      // contains the same field label.
      return !Array.from(
        element.querySelectorAll(selector)
      ).some((child) => {
        const childText = getElementText(child);

        return labels.some((label) =>
          isExactLabelOrInlineField(
            childText,
            label
          )
        );
      });
    })
    .sort((a, b) => {
      const aText = getElementText(a);
      const bText = getElementText(b);

      const aLabelOnly = labels.some(
        (label) => isLabelOnly(aText, label)
      );
      const bLabelOnly = labels.some(
        (label) => isLabelOnly(bText, label)
      );

      if (aLabelOnly !== bLabelOnly) {
        return aLabelOnly ? -1 : 1;
      }

      return aText.length - bText.length;
    });

  return candidates[0] || null;
}

function setDescriptionFieldValue(
  editor,
  labelElement,
  labels,
  value
) {
  const labelText = getElementText(labelElement);
  const matchingLabel = labels.find((label) =>
    isExactLabelOrInlineField(
      labelText,
      label
    )
  );

  if (!matchingLabel) {
    return false;
  }

  // Inline template:
  // Label: Columbia
  //
  // Replace only the text after the colon.
  if (!isLabelOnly(labelText, matchingLabel)) {
    return replaceInlineFieldValue(
      labelElement,
      matchingLabel,
      value
    );
  }

  // Blank label template:
  //
  // Artist:
  //
  // Keep the value on the same visual line:
  //
  // Artist: Miles Davis
  //
  // The exact label element has already been selected, so appending
  // here cannot overwrite the neighbouring Title, Format or Label fields.
  const labelLine = getFieldLineContainer(
    editor,
    labelElement
  ) || labelElement;

  // Clean up a value line inserted by version 0.8, if present.
  const nextLine = getNextMeaningfulElement(
    labelLine
  );

  if (
    nextLine &&
    !isKnownFieldLabelElement(nextLine) &&
    isSafeLegacyValueLine(nextLine)
  ) {
    nextLine.remove();
  }

  appendInlineValue(
    labelElement,
    value
  );

  dispatchEditingEvents(labelElement);
  return true;
}

function appendInlineValue(element, value) {
  const ownerDocument =
    element.ownerDocument || document;

  // Remove trailing whitespace so the result is consistently:
  // "Artist: Miles Davis"
  const textNodes = getTextNodes(
    element,
    ownerDocument
  );

  if (textNodes.length) {
    const finalNode =
      textNodes[textNodes.length - 1];

    finalNode.nodeValue =
      String(finalNode.nodeValue || "")
        .replace(/\s+$/, "");
  }

  element.appendChild(
    ownerDocument.createTextNode(` ${value}`)
  );
}

function isSafeLegacyValueLine(element) {
  const text = getElementText(element);

  if (!text || text.length > 250) {
    return false;
  }

  // Never remove a recognised field label.
  if (isKnownFieldLabelElement(element)) {
    return false;
  }

  // Version 0.8 created simple cloned blocks containing only a value.
  // Restrict cleanup to plain short blocks without nested controls,
  // links, images or other meaningful template structure.
  if (
    element.querySelector(
      "input, textarea, select, button, a, img, table, iframe"
    )
  ) {
    return false;
  }

  return ["DIV", "P", "LI", "SPAN"].includes(
    element.tagName
  );
}

function replaceInlineFieldValue(
  element,
  label,
  value
) {
  const ownerDocument =
    element.ownerDocument || document;
  const textNodes = getTextNodes(
    element,
    ownerDocument
  );

  if (!textNodes.length) {
    return false;
  }

  const fullText = textNodes
    .map((node) => node.nodeValue || "")
    .join("");

  const expression = buildSingleLabelRegex(
    label,
    false
  );
  const match = fullText.match(expression);

  if (!match || match.index === undefined) {
    return false;
  }

  const valueStart =
    match.index + match[0].length;

  const startPosition = mapTextOffset(
    textNodes,
    valueStart
  );
  const endPosition = mapTextOffset(
    textNodes,
    fullText.length
  );

  if (!startPosition || !endPosition) {
    return false;
  }

  const range = ownerDocument.createRange();
  range.setStart(
    startPosition.node,
    startPosition.offset
  );
  range.setEnd(
    endPosition.node,
    endPosition.offset
  );
  range.deleteContents();
  range.insertNode(
    ownerDocument.createTextNode(` ${value}`)
  );

  dispatchEditingEvents(element);
  return true;
}

function getFieldLineContainer(
  editor,
  labelElement
) {
  const blockTags = new Set([
    "P",
    "DIV",
    "LI",
    "TD",
    "TH"
  ]);

  let current = labelElement;

  while (
    current &&
    current !== editor
  ) {
    if (
      blockTags.has(current.tagName) &&
      current.parentElement
    ) {
      // Do not climb into a broad block that includes several fields.
      const currentText = getElementText(current);

      if (currentText.length <= 250) {
        return current;
      }
    }

    current = current.parentElement;
  }

  if (labelElement.parentElement === editor) {
    return labelElement;
  }

  return null;
}

function getNextMeaningfulElement(element) {
  let sibling = element.nextElementSibling;

  while (sibling) {
    const text = getElementText(sibling);

    if (text || isKnownFieldLabelElement(sibling)) {
      return sibling;
    }

    sibling = sibling.nextElementSibling;
  }

  return null;
}

function isKnownFieldLabelElement(element) {
  const text = getElementText(element);

  return ALL_DESCRIPTION_FIELDS.some((field) =>
    field.labels.some((label) =>
      isExactLabelOrInlineField(
        text,
        label
      )
    )
  );
}

function isExactLabelOrInlineField(
  text,
  label
) {
  return buildSingleLabelRegex(
    label,
    true
  ).test(cleanLineText(text));
}

function isLabelOnly(text, label) {
  const flexibleLabel = escapeRegExp(label)
    .replace(/\\\./g, "\\.?")
    .replace(/\s+/g, "\\s*");

  return new RegExp(
    `^\\s*${flexibleLabel}\\s*:\\s*$`,
    "i"
  ).test(cleanLineText(text));
}

function buildSingleLabelRegex(
  label,
  allowValue
) {
  const flexibleLabel = escapeRegExp(label)
    .replace(/\\\./g, "\\.?")
    .replace(/\s+/g, "\\s*");

  return new RegExp(
    allowValue
      ? `^\\s*${flexibleLabel}\\s*:\\s*.*$`
      : `^\\s*${flexibleLabel}\\s*:\\s*`,
    "i"
  );
}

function getElementText(element) {
  return cleanLineText(
    element.innerText ||
    element.textContent ||
    ""
  );
}

function buildLabelRegex(label, capturePrefix) {
  const flexibleLabel = escapeRegExp(label)
    // Treat full stops in labels as optional so Cat No, Cat. No and
    // Cat. No. can all match safely.
    .replace(/\\\./g, "\\.?")
    .replace(/\s+/g, "\\s*");

  if (capturePrefix) {
    return new RegExp(
      `^(\\s*${flexibleLabel}\\s*:\\s*).*$`,
      "im"
    );
  }

  return new RegExp(
    `^\\s*${flexibleLabel}\\s*:\\s*`,
    "i"
  );
}

function getTextNodes(root, ownerDocument) {
  const walker = ownerDocument.createTreeWalker(
    root,
    NodeFilter.SHOW_TEXT,
    {
      acceptNode(node) {
        if (!node.nodeValue) {
          return NodeFilter.FILTER_REJECT;
        }

        const parent = node.parentElement;

        if (
          parent &&
          ["SCRIPT", "STYLE", "NOSCRIPT"].includes(parent.tagName)
        ) {
          return NodeFilter.FILTER_REJECT;
        }

        return NodeFilter.FILTER_ACCEPT;
      }
    }
  );

  const nodes = [];
  let current;

  while ((current = walker.nextNode())) {
    nodes.push(current);
  }

  return nodes;
}

function mapTextOffset(nodes, targetOffset) {
  let traversed = 0;

  for (const node of nodes) {
    const length = (node.nodeValue || "").length;

    if (targetOffset <= traversed + length) {
      return {
        node,
        offset: targetOffset - traversed
      };
    }

    traversed += length;
  }

  const finalNode = nodes[nodes.length - 1];

  if (!finalNode) {
    return null;
  }

  return {
    node: finalNode,
    offset: (finalNode.nodeValue || "").length
  };
}

function setEditableValue(element, value) {
  if (element.isContentEditable) {
    element.textContent = value;
    dispatchEditingEvents(element);
    return;
  }

  const prototype =
    element instanceof HTMLTextAreaElement
      ? HTMLTextAreaElement.prototype
      : HTMLInputElement.prototype;

  const descriptor = Object.getOwnPropertyDescriptor(
    prototype,
    "value"
  );

  if (descriptor?.set) {
    descriptor.set.call(element, value);
  } else {
    element.value = value;
  }

  dispatchEditingEvents(element);
}

function dispatchEditingEvents(element) {
  if (
    !element ||
    typeof element.dispatchEvent !== "function"
  ) {
    return;
  }

  element.dispatchEvent(
    new InputEvent("input", {
      bubbles: true,
      inputType: "insertText"
    })
  );

  element.dispatchEvent(
    new Event("change", {
      bubbles: true
    })
  );

  element.dispatchEvent(
    new FocusEvent("blur", {
      bubbles: true
    })
  );
}

function scrollToDescriptionEditor(editor) {
  if (!editor) {
    return;
  }

  editor.scrollIntoView({
    behavior: "smooth",
    block: "center"
  });
}

function getEditorText(editor) {
  if (
    editor instanceof HTMLTextAreaElement ||
    editor instanceof HTMLInputElement
  ) {
    return editor.value;
  }

  return editor.innerText || editor.textContent || "";
}

function isVisible(element) {
  const view =
    element.ownerDocument?.defaultView || window;
  const style = view.getComputedStyle(element);
  const rectangle = element.getBoundingClientRect();

  return (
    style.display !== "none" &&
    style.visibility !== "hidden" &&
    rectangle.width > 0 &&
    rectangle.height > 0
  );
}

function cleanLineText(value) {
  return String(value || "")
    .replace(/\u00a0/g, " ")
    .replace(/[ \t]+/g, " ")
    .trim();
}

function cleanText(value) {
  return String(value || "")
    .replace(/\u00a0/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function escapeRegExp(value) {
  return String(value).replace(
    /[.*+?^${}()|[\]\\]/g,
    "\\$&"
  );
}


function initialiseConditionAssistant() {
  if (
    !document.body ||
    document.getElementById(
      "discogs-ebay-condition-assistant-host"
    )
  ) {
    return;
  }

  const host = document.createElement("div");
  host.id =
    "discogs-ebay-condition-assistant-host";

  Object.assign(host.style, {
    position: "fixed",
    top: "12px",
    left: "12px",
    zIndex: "2147483646"
  });

  const shadow = host.attachShadow({
    mode: "open"
  });

  shadow.innerHTML = `
    <style>
      :host {
        all: initial;
      }

      * {
        box-sizing: border-box;
      }

      .panel {
        width: 330px;
        overflow: hidden;
        border: 1px solid #c7c7c7;
        border-radius: 10px;
        background: #ffffff;
        color: #191919;
        box-shadow:
          0 10px 32px rgba(0, 0, 0, 0.22);
        font-family:
          Arial, Helvetica, sans-serif;
        font-size: 13px;
      }

      .header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        min-height: 42px;
        padding: 10px 12px;
        background: #f4f4f4;
        border-bottom: 1px solid #d8d8d8;
      }

      .header-title {
        margin: 0;
        font-size: 14px;
        font-weight: 700;
      }

      .collapse-button {
        width: 28px;
        height: 26px;
        padding: 0;
        border: 1px solid #b7b7b7;
        border-radius: 5px;
        background: #ffffff;
        color: #191919;
        cursor: pointer;
        font-size: 16px;
        line-height: 1;
      }

      .body {
        padding: 12px;
      }

      .body[hidden] {
        display: none;
      }

      .section-title {
        margin: 0 0 10px;
        font-size: 15px;
        font-weight: 700;
      }

      .grade-card {
        margin-bottom: 12px;
        padding: 10px;
        border: 1px solid #dedede;
        border-radius: 8px;
        background: #fafafa;
      }

      .grade-card-title {
        margin: 0 0 8px;
        font-size: 13px;
        font-weight: 700;
      }

      .grade-controls {
        display: grid;
        grid-template-columns:
          minmax(0, 1fr) 32px 48px 32px;
        gap: 6px;
        align-items: center;
      }

      select,
      input {
        width: 100%;
        border: 1px solid #b8b8b8;
        border-radius: 5px;
        background: #ffffff;
        color: #191919;
        font: inherit;
      }

      select {
        height: 34px;
        padding: 0 8px;
      }

      input {
        height: 34px;
        margin-top: 8px;
        padding: 0 9px;
      }

      .step-button {
        width: 32px;
        height: 34px;
        padding: 0;
        border: 1px solid #a9a9a9;
        border-radius: 5px;
        background: #ffffff;
        color: #191919;
        cursor: pointer;
        font-size: 18px;
        font-weight: 700;
      }

      .plus-count {
        text-align: center;
        font-weight: 700;
      }

      .preview {
        margin-top: 8px;
        overflow-wrap: anywhere;
        color: #333333;
        font-size: 12px;
        line-height: 1.35;
      }

      .apply-button {
        width: 100%;
        min-height: 38px;
        border: 0;
        border-radius: 6px;
        background: #3665f3;
        color: #ffffff;
        cursor: pointer;
        font: inherit;
        font-weight: 700;
      }

      .apply-button:disabled {
        cursor: wait;
        opacity: 0.7;
      }

      .status {
        min-height: 18px;
        margin: 8px 0 0;
        color: #333333;
        font-size: 12px;
        line-height: 1.35;
      }

      .status.error {
        color: #a40000;
      }

      .status.success {
        color: #116329;
      }

      @media (prefers-color-scheme: dark) {
        .panel {
          border-color: #555555;
          background: #242424;
          color: #f5f5f5;
        }

        .header {
          border-bottom-color: #555555;
          background: #303030;
        }

        .collapse-button,
        select,
        input,
        .step-button {
          border-color: #666666;
          background: #333333;
          color: #f5f5f5;
        }

        .grade-card {
          border-color: #555555;
          background: #2b2b2b;
        }

        .preview,
        .status {
          color: #dddddd;
        }

        .status.error {
          color: #ff9d9d;
        }

        .status.success {
          color: #8ee5a8;
        }
      }
    </style>

    <section class="panel">
      <header class="header">
        <h2 class="header-title">
          Vinyl Listing Assistant
        </h2>
        <button
          class="collapse-button"
          id="condition-collapse"
          type="button"
          aria-label="Collapse condition assistant"
        >−</button>
      </header>

      <div class="body" id="condition-body">
        <h3 class="section-title">Condition</h3>

        <section class="grade-card">
          <h4 class="grade-card-title">
            Vinyl
          </h4>

          <div class="grade-controls">
            <select
              id="vinyl-grade"
              aria-label="Vinyl grade"
            >
              <option>Good</option>
              <option>Very Good</option>
              <option>Excellent</option>
            </select>

            <button
              class="step-button"
              id="vinyl-minus"
              type="button"
              aria-label="Remove one vinyl plus"
            >−</button>

            <span
              class="plus-count"
              id="vinyl-plus-count"
            >0/4</span>

            <button
              class="step-button"
              id="vinyl-plus"
              type="button"
              aria-label="Add one vinyl plus"
            >+</button>
          </div>

          <input
            id="vinyl-notes"
            type="text"
            autocomplete="off"
            placeholder="Vinyl description"
            aria-label="Vinyl condition description"
          >

          <div
            class="preview"
            id="vinyl-preview"
          ></div>
        </section>

        <section class="grade-card">
          <h4 class="grade-card-title">
            Sleeve
          </h4>

          <div class="grade-controls">
            <select
              id="sleeve-grade"
              aria-label="Sleeve grade"
            >
              <option>Good</option>
              <option>Very Good</option>
              <option>Excellent</option>
            </select>

            <button
              class="step-button"
              id="sleeve-minus"
              type="button"
              aria-label="Remove one sleeve plus"
            >−</button>

            <span
              class="plus-count"
              id="sleeve-plus-count"
            >0/4</span>

            <button
              class="step-button"
              id="sleeve-plus"
              type="button"
              aria-label="Add one sleeve plus"
            >+</button>
          </div>

          <input
            id="sleeve-notes"
            type="text"
            autocomplete="off"
            placeholder="Sleeve description"
            aria-label="Sleeve condition description"
          >

          <div
            class="preview"
            id="sleeve-preview"
          ></div>
        </section>

        <button
          class="apply-button"
          id="condition-apply"
          type="button"
        >
          Apply condition
        </button>

        <p
          class="status"
          id="condition-status"
          role="status"
        ></p>
      </div>
    </section>
  `;

  document.body.appendChild(host);

  initialiseConditionAssistantControls(
    shadow
  );
}

async function initialiseConditionAssistantControls(
  shadow
) {
  const stored = await browser.storage.local.get(
    CONDITION_ASSISTANT_STORAGE_KEY
  );

  const state = normaliseConditionAssistantState(
    stored[CONDITION_ASSISTANT_STORAGE_KEY]
  );

  const controls = {
    body: shadow.getElementById("condition-body"),
    collapse:
      shadow.getElementById("condition-collapse"),
    apply:
      shadow.getElementById("condition-apply"),
    status:
      shadow.getElementById("condition-status"),
    vinyl: {
      grade:
        shadow.getElementById("vinyl-grade"),
      notes:
        shadow.getElementById("vinyl-notes"),
      minus:
        shadow.getElementById("vinyl-minus"),
      plus:
        shadow.getElementById("vinyl-plus"),
      plusCount:
        shadow.getElementById(
          "vinyl-plus-count"
        ),
      preview:
        shadow.getElementById(
          "vinyl-preview"
        )
    },
    sleeve: {
      grade:
        shadow.getElementById("sleeve-grade"),
      notes:
        shadow.getElementById("sleeve-notes"),
      minus:
        shadow.getElementById("sleeve-minus"),
      plus:
        shadow.getElementById("sleeve-plus"),
      plusCount:
        shadow.getElementById(
          "sleeve-plus-count"
        ),
      preview:
        shadow.getElementById(
          "sleeve-preview"
        )
    }
  };

  controls.vinyl.grade.value =
    state.vinyl.grade;
  controls.vinyl.notes.value =
    state.vinyl.notes;
  controls.sleeve.grade.value =
    state.sleeve.grade;
  controls.sleeve.notes.value =
    state.sleeve.notes;

  controls.body.hidden = state.collapsed;
  controls.collapse.textContent =
    state.collapsed ? "+" : "−";

  bindConditionSectionControls(
    "vinyl",
    state,
    controls
  );
  bindConditionSectionControls(
    "sleeve",
    state,
    controls
  );

  controls.collapse.addEventListener(
    "click",
    async () => {
      state.collapsed = !state.collapsed;
      controls.body.hidden =
        state.collapsed;
      controls.collapse.textContent =
        state.collapsed ? "+" : "−";

      await saveConditionAssistantState(
        state
      );
    }
  );

  controls.apply.addEventListener(
    "click",
    async () => {
      controls.apply.disabled = true;
      setConditionPanelStatus(
        controls.status,
        "Applying condition...",
        ""
      );

      try {
        await saveConditionAssistantState(
          state
        );

        const result =
          await applyConditionAssistantState(
            state
          );

        const missingDescriptionFields =
          result.descriptionResult
            .missingFields || [];

        let message =
          "Seller Notes and item-description " +
          "condition fields were updated.";

        if (
          missingDescriptionFields.length
        ) {
          message +=
            " Missing description fields: " +
            missingDescriptionFields.join(
              ", "
            ) +
            ".";
        }

        setConditionPanelStatus(
          controls.status,
          message,
          missingDescriptionFields.length
            ? ""
            : "success"
        );

        showToast(
          message +
            " Review the listing before saving.",
          missingDescriptionFields.length
            ? "warning"
            : "success"
        );
      } catch (error) {
        const message =
          error.message ||
          "Unable to apply the condition.";

        setConditionPanelStatus(
          controls.status,
          message,
          "error"
        );
        showToast(message, "error");
        console.error(error);
      } finally {
        controls.apply.disabled = false;
      }
    }
  );

  renderConditionAssistant(
    state,
    controls
  );
}

function bindConditionSectionControls(
  sectionName,
  state,
  controls
) {
  const section =
    controls[sectionName];

  section.grade.addEventListener(
    "change",
    async () => {
      state[sectionName].grade =
        section.grade.value;

      renderConditionAssistant(
        state,
        controls
      );
      await saveConditionAssistantState(
        state
      );
    }
  );

  section.notes.addEventListener(
    "input",
    () => {
      state[sectionName].notes =
        section.notes.value;

      renderConditionAssistant(
        state,
        controls
      );
      queueConditionStateSave(state);
    }
  );

  section.plus.addEventListener(
    "click",
    async () => {
      state[sectionName].pluses =
        Math.min(
          MAX_GRADE_PLUSES,
          state[sectionName].pluses + 1
        );

      renderConditionAssistant(
        state,
        controls
      );
      await saveConditionAssistantState(
        state
      );
    }
  );

  section.minus.addEventListener(
    "click",
    async () => {
      state[sectionName].pluses =
        Math.max(
          0,
          state[sectionName].pluses - 1
        );

      renderConditionAssistant(
        state,
        controls
      );
      await saveConditionAssistantState(
        state
      );
    }
  );
}

let conditionStateSaveTimer = null;

function queueConditionStateSave(state) {
  window.clearTimeout(
    conditionStateSaveTimer
  );

  conditionStateSaveTimer =
    window.setTimeout(() => {
      saveConditionAssistantState(state);
    }, 250);
}

async function saveConditionAssistantState(
  state
) {
  await browser.storage.local.set({
    [CONDITION_ASSISTANT_STORAGE_KEY]:
      normaliseConditionAssistantState(state)
  });
}

function normaliseConditionAssistantState(
  candidate
) {
  const source =
    candidate &&
    typeof candidate === "object"
      ? candidate
      : {};

  return {
    vinyl: normaliseConditionSection(
      source.vinyl,
      DEFAULT_CONDITION_ASSISTANT_STATE
        .vinyl
    ),
    sleeve: normaliseConditionSection(
      source.sleeve,
      DEFAULT_CONDITION_ASSISTANT_STATE
        .sleeve
    ),
    collapsed:
      typeof source.collapsed === "boolean"
        ? source.collapsed
        : false
  };
}

function normaliseConditionSection(
  section,
  fallback
) {
  const validGrades = new Set([
    "Good",
    "Very Good",
    "Excellent"
  ]);

  const source =
    section &&
    typeof section === "object"
      ? section
      : {};

  const grade = validGrades.has(
    source.grade
  )
    ? source.grade
    : fallback.grade;

  const parsedPluses = Number(
    source.pluses
  );

  const pluses = Number.isFinite(
    parsedPluses
  )
    ? Math.max(
        0,
        Math.min(
          MAX_GRADE_PLUSES,
          Math.trunc(parsedPluses)
        )
      )
    : fallback.pluses;

  return {
    grade,
    pluses,
    notes:
      typeof source.notes === "string"
        ? source.notes
        : fallback.notes
  };
}

function renderConditionAssistant(
  state,
  controls
) {
  for (const sectionName of [
    "vinyl",
    "sleeve"
  ]) {
    const sectionState =
      state[sectionName];
    const sectionControls =
      controls[sectionName];

    sectionControls.plusCount.textContent =
      `${sectionState.pluses}/4`;

    sectionControls.preview.textContent =
      buildConditionValue(
        sectionState,
        sectionName === "sleeve"
      );
  }
}

function formatConditionGrade(
  grade,
  pluses
) {
  const safePluses = Math.max(
    0,
    Math.min(
      MAX_GRADE_PLUSES,
      Math.trunc(Number(pluses) || 0)
    )
  );

  const plusText =
    "+".repeat(safePluses);

  if (
    grade === "Excellent" &&
    safePluses === MAX_GRADE_PLUSES
  ) {
    return (
      `Excellent${plusText} ` +
      "to Near Mint"
    );
  }

  return `${grade}${plusText}`;
}

function buildConditionValue(
  section,
  isSleeve
) {
  const grade = formatConditionGrade(
    section.grade,
    section.pluses
  );

  const notes = cleanConditionNotes(
    section.notes
  );

  let value = notes
    ? `${grade}, ${notes}`
    : grade;

  if (
    isSleeve &&
    !/\(see associated images\)$/i.test(
      value
    )
  ) {
    value += " (see associated images)";
  }

  return value;
}

function cleanConditionNotes(value) {
  return String(value || "")
    .replace(/\u00a0/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/[.\s]+$/g, "");
}

function setConditionPanelStatus(
  element,
  message,
  type
) {
  element.textContent = message;
  element.className =
    type
      ? `status ${type}`
      : "status";
}

async function applyConditionAssistantState(
  state
) {
  const recordCondition =
    buildConditionValue(
      state.vinyl,
      false
    );

  const sleeveCondition =
    buildConditionValue(
      state.sleeve,
      true
    );

  // The condition-description / Seller Notes field is
  // deliberately updated first.
  const conditionField =
    findConditionDescriptionFieldAcrossDocuments();

  if (!conditionField) {
    throw new Error(
      "Could not find the Seller Notes or " +
      "Condition Description field."
    );
  }

  fillSellerNotesField(
    conditionField,
    recordCondition,
    sleeveCondition
  );

  // Only after Seller Notes has been updated are the same
  // values copied into the existing item-description fields.
  const descriptionResult =
    fillConditionFieldsAcrossDocuments({
      recordCondition,
      sleeveCondition
    });

  return {
    recordCondition,
    sleeveCondition,
    descriptionResult
  };
}

function getAccessibleDocuments() {
  const documents = [];
  const visited = new Set();

  function collect(currentDocument) {
    if (
      !currentDocument ||
      visited.has(currentDocument)
    ) {
      return;
    }

    visited.add(currentDocument);
    documents.push(currentDocument);

    for (
      const frame of
      currentDocument.querySelectorAll(
        "iframe"
      )
    ) {
      try {
        if (frame.contentDocument) {
          collect(frame.contentDocument);
        }
      } catch (error) {
        console.debug(
          "Could not inspect an eBay iframe:",
          error
        );
      }
    }
  }

  collect(document);
  return documents;
}

function findConditionDescriptionFieldAcrossDocuments() {
  const candidates = [];

  for (
    const currentDocument of
    getAccessibleDocuments()
  ) {
    const selectors = [
      "textarea",
      'input[type="text"]',
      'input:not([type])',
      '[contenteditable="true"]',
      '[role="textbox"]'
    ];

    for (
      const element of
      currentDocument.querySelectorAll(
        selectors.join(",")
      )
    ) {
      if (!isVisible(element)) {
        continue;
      }

      const score =
        scoreConditionDescriptionField(
          element,
          currentDocument
        );

      if (score > 0) {
        candidates.push({
          element,
          score
        });
      }
    }
  }

  candidates.sort(
    (a, b) => b.score - a.score
  );

  return candidates[0]?.element || null;
}

function scoreConditionDescriptionField(
  element,
  ownerDocument
) {
  const attributes = [
    element.id,
    element.getAttribute("name"),
    element.getAttribute("aria-label"),
    element.getAttribute("placeholder"),
    element.getAttribute("data-testid"),
    element.getAttribute("title")
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();

  const value =
    getEditableFieldText(element)
      .toLowerCase();

  const associatedText =
    getAssociatedFieldText(
      element,
      ownerDocument
    ).toLowerCase();

  const searchable =
    `${attributes} ${associatedText}`;

  let score = 0;

  if (
    /vinyl\s*grade\s*:/.test(value)
  ) {
    score += 120;
  }

  if (
    /sleeve\s*grade\s*:/.test(value)
  ) {
    score += 120;
  }

  if (/seller\s*notes?/.test(searchable)) {
    score += 100;
  }

  if (
    /condition\s*description/.test(
      searchable
    )
  ) {
    score += 95;
  }

  if (
    /condition\s*(details?|notes?)/.test(
      searchable
    )
  ) {
    score += 70;
  }

  if (
    /item\s*description/.test(searchable) &&
    !/condition/.test(searchable)
  ) {
    score -= 120;
  }

  if (
    /\btitle\b/.test(searchable) &&
    !/condition/.test(searchable)
  ) {
    score -= 80;
  }

  return score;
}

function getAssociatedFieldText(
  element,
  ownerDocument
) {
  const values = [];

  if (element.id) {
    const safeId =
      typeof CSS !== "undefined" &&
      typeof CSS.escape === "function"
        ? CSS.escape(element.id)
        : element.id.replace(
            /["\\]/g,
            "\\$&"
          );

    const labels =
      ownerDocument.querySelectorAll(
        `label[for="${safeId}"]`
      );

    for (const label of labels) {
      values.push(
        label.innerText ||
        label.textContent ||
        ""
      );
    }
  }

  const closestLabel =
    element.closest("label");

  if (closestLabel) {
    values.push(
      closestLabel.innerText ||
      closestLabel.textContent ||
      ""
    );
  }

  const parent = element.parentElement;

  if (parent) {
    values.push(
      String(
        parent.innerText ||
        parent.textContent ||
        ""
      ).slice(0, 500)
    );
  }

  return values.join(" ");
}

function getEditableFieldText(element) {
  if (
    element instanceof HTMLInputElement ||
    element instanceof HTMLTextAreaElement
  ) {
    return element.value || "";
  }

  return (
    element.innerText ||
    element.textContent ||
    ""
  );
}

function fillSellerNotesField(
  field,
  recordCondition,
  sleeveCondition
) {
  const existingText =
    getEditableFieldText(field);

  let updatedText = upsertConditionLine(
    existingText,
    [
      "Vinyl Grade"
    ],
    "Vinyl Grade",
    recordCondition
  );

  updatedText = upsertConditionLine(
    updatedText,
    [
      "Sleeve Grade"
    ],
    "Sleeve Grade",
    sleeveCondition
  );

  const maxLength =
    Number(field.maxLength);

  if (
    Number.isFinite(maxLength) &&
    maxLength > 0 &&
    updatedText.length > maxLength
  ) {
    throw new Error(
      "The generated condition description " +
      `is ${updatedText.length} characters, ` +
      `but the field limit is ${maxLength}.`
    );
  }

  setEditableValue(
    field,
    updatedText
  );
}

function upsertConditionLine(
  text,
  labels,
  canonicalLabel,
  value
) {
  const source = String(text || "");
  const alternatives = labels
    .map((label) =>
      escapeRegExp(label)
        .replace(/\s+/g, "\\s*")
    )
    .join("|");

  const expression = new RegExp(
    `^(\\s*(?:${alternatives})\\s*:\\s*).*$`,
    "im"
  );

  const sentence =
    `${cleanConditionNotes(value)}.`;

  if (expression.test(source)) {
    return source.replace(
      expression,
      (match, prefix) =>
        `${prefix}${sentence}`
    );
  }

  const separator =
    source.trim()
      ? source.endsWith("\n")
        ? ""
        : "\n"
      : "";

  return (
    `${source}${separator}` +
    `${canonicalLabel}: ${sentence}`
  );
}

function fillConditionFieldsAcrossDocuments(
  values
) {
  let bestResult = {
    foundEditor: false,
    updatedFields: [],
    missingFields:
      CONDITION_DESCRIPTION_FIELDS.map(
        (field) => field.displayName
      ),
    editor: null
  };

  for (
    const currentDocument of
    getAccessibleDocuments()
  ) {
    const editors =
      findDescriptionEditors(
        currentDocument
      );

    for (const editor of editors) {
      const result =
        fillConditionFieldsInEditor(
          editor,
          values
        );

      if (
        result.updatedFields.length >
        bestResult.updatedFields.length
      ) {
        bestResult = {
          ...result,
          foundEditor: true,
          editor
        };
      }

      if (
        result.updatedFields.length ===
        CONDITION_DESCRIPTION_FIELDS.length
      ) {
        return bestResult;
      }
    }
  }

  return bestResult;
}

function fillConditionFieldsInEditor(
  editor,
  values
) {
  if (
    editor instanceof HTMLInputElement ||
    editor instanceof HTMLTextAreaElement
  ) {
    return fillPlainConditionFields(
      editor,
      values
    );
  }

  return fillRichConditionFields(
    editor,
    values
  );
}

function fillPlainConditionFields(
  editor,
  values
) {
  let text = editor.value;
  const updatedFields = [];
  const missingFields = [];

  for (
    const field of
    CONDITION_DESCRIPTION_FIELDS
  ) {
    const value = cleanText(
      values[field.key]
    );

    if (!value) {
      missingFields.push(
        field.displayName
      );
      continue;
    }

    const replacement =
      replaceLabelledLine(
        text,
        field.labels,
        value
      );

    if (replacement.changed) {
      text = replacement.text;
      updatedFields.push(
        field.displayName
      );
    } else {
      missingFields.push(
        field.displayName
      );
    }
  }

  if (updatedFields.length) {
    setEditableValue(editor, text);
  }

  return {
    updatedFields,
    missingFields
  };
}

function fillRichConditionFields(
  editor,
  values
) {
  const updatedFields = [];
  const missingFields = [];

  for (
    const field of
    CONDITION_DESCRIPTION_FIELDS
  ) {
    const value = cleanText(
      values[field.key]
    );

    const labelElement =
      findExactLabelElement(
        editor,
        field.labels
      );

    if (!value || !labelElement) {
      missingFields.push(
        field.displayName
      );
      continue;
    }

    const changed =
      setDescriptionFieldValue(
        editor,
        labelElement,
        field.labels,
        value
      );

    if (changed) {
      updatedFields.push(
        field.displayName
      );
    } else {
      missingFields.push(
        field.displayName
      );
    }
  }

  if (updatedFields.length) {
    dispatchEditingEvents(editor);
  }

  return {
    updatedFields,
    missingFields
  };
}

function showToast(message, type) {
  document.getElementById("discogs-ebay-title-toast")?.remove();

  const toast = document.createElement("div");
  toast.id = "discogs-ebay-title-toast";
  toast.textContent = message;

  const backgrounds = {
    success: "#173d2b",
    warning: "#665200",
    error: "#5a1f1f"
  };

  Object.assign(toast.style, {
    position: "fixed",
    top: "20px",
    right: "20px",
    zIndex: "2147483647",
    maxWidth: "620px",
    padding: "14px 18px",
    borderRadius: "8px",
    background: backgrounds[type] || backgrounds.error,
    color: "#ffffff",
    fontFamily: "Arial, sans-serif",
    fontSize: "14px",
    lineHeight: "1.4",
    boxShadow: "0 6px 24px rgba(0, 0, 0, 0.3)"
  });

  document.body.appendChild(toast);

  window.setTimeout(() => {
    toast.remove();
  }, type === "error" ? 8500 : 6500);
}

if (document.readyState === "loading") {
  document.addEventListener(
    "DOMContentLoaded",
    initialiseConditionAssistant,
    {
      once: true
    }
  );
} else {
  initialiseConditionAssistant();
}

